[
    {
        "id": "tab_aula_mqtt",
        "type": "tab",
        "label": "Aula MQTT",
        "disabled": false,
        "info": "Fluxo IoT: MQTT IN -> Function -> Gauge + Chart\nTopico: casa/sala/temperatura"
    },
    {
        "id": "ui_base_main",
        "type": "ui_base",
        "theme": {
            "name": "theme-light",
            "lightTheme": {
                "default": "#0094CE",
                "baseColor": "#0094CE",
                "baseFont": "-apple-system,BlinkMacSystemFont,Segoe UI",
                "edited": false,
                "reset": false
            },
            "themeState": {
                "base-color": {"default": "#0094CE", "value": "#0094CE", "edited": false},
                "page-titlebar-backgroundColor": {"value": "#0094CE", "edited": false},
                "page-backgroundColor": {"value": "#fafafa", "edited": false},
                "page-sidebar-backgroundColor": {"value": "#ffffff", "edited": false},
                "group-textColor": {"value": "#1bbfff", "edited": false},
                "group-borderColor": {"value": "#ffffff", "edited": false},
                "group-backgroundColor": {"value": "#ffffff", "edited": false},
                "widget-textColor": {"value": "#111111", "edited": false},
                "widget-backgroundColor": {"value": "#0094ce", "edited": false},
                "widget-borderColor": {"value": "#ffffff", "edited": false},
                "base-font": {"value": "-apple-system,BlinkMacSystemFont,Segoe UI"}
            },
            "angularTheme": {"primary": "indigo", "accents": "blue", "warn": "red", "background": "grey"}
        },
        "site": {
            "name": "Node-RED Dashboard",
            "hideToolbar": "false",
            "allowSwipe": "false",
            "lockMenu": "false",
            "allowTempTheme": "true",
            "dateFormat": "DD/MM/YYYY",
            "sizes": {"sx": 48, "sy": 48, "gx": 6, "gy": 6, "cx": 6, "cy": 6, "px": 0, "py": 0}
        }
    },
    {
        "id": "ui_tab_sala",
        "type": "ui_tab",
        "name": "Sala",
        "icon": "dashboard",
        "order": 1,
        "disabled": false,
        "hidden": false
    },
    {
        "id": "ui_group_temp",
        "type": "ui_group",
        "name": "Temperatura",
        "tab": "ui_tab_sala",
        "order": 1,
        "disp": true,
        "width": "8",
        "collapse": false,
        "className": ""
    },
    {
        "id": "broker_local",
        "type": "mqtt-broker",
        "name": "Broker Local",
        "broker": "localhost",
        "port": "1883",
        "clientid": "",
        "autoConnect": true,
        "usetls": false,
        "protocolVersion": "4",
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthPayload": "",
        "birthMsg": {},
        "closeTopic": "",
        "closeQos": "0",
        "closePayload": "",
        "closeMsg": {},
        "willTopic": "",
        "willQos": "0",
        "willPayload": "",
        "willMsg": {},
        "userProps": "",
        "sessionExpiry": ""
    },
    {
        "id": "mqtt_in_temp",
        "type": "mqtt in",
        "z": "tab_aula_mqtt",
        "name": "MQTT IN",
        "topic": "casa/sala/temperatura",
        "qos": "0",
        "datatype": "auto-detect",
        "broker": "broker_local",
        "nl": false,
        "rap": true,
        "rh": 0,
        "inputs": 0,
        "x": 140,
        "y": 200,
        "wires": [["function_extrai"]]
    },
    {
        "id": "function_extrai",
        "type": "function",
        "z": "tab_aula_mqtt",
        "name": "Extrai Temperatura",
        "func": "let dados;\n\ntry {\n    dados = typeof msg.payload === \"string\"\n        ? JSON.parse(msg.payload)\n        : msg.payload;\n} catch (e) {\n    node.warn(\"JSON invalido recebido\");\n    return null;\n}\n\nlet temperatura = Number(dados.temperatura);\n\nif (isNaN(temperatura)) {\n    node.warn(\"Campo temperatura invalido ou ausente\");\n    return null;\n}\n\nlet msgGauge = { payload: temperatura, topic: \"Temperatura\" };\nlet msgChart = { payload: temperatura, topic: \"Temperatura\" };\n\nreturn [msgGauge, msgChart];\n",
        "outputs": 2,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 360,
        "y": 200,
        "wires": [["gauge_temp"], ["chart_temp"]]
    },
    {
        "id": "gauge_temp",
        "type": "ui_gauge",
        "z": "tab_aula_mqtt",
        "name": "Gauge Temperatura",
        "group": "ui_group_temp",
        "order": 1,
        "width": 0,
        "height": 0,
        "gtype": "gage",
        "title": "Temperatura",
        "label": "°C",
        "format": "{{value}}",
        "min": 0,
        "max": "50",
        "colors": ["#00b500", "#e6e600", "#ca3838"],
        "seg1": "20",
        "seg2": "35",
        "diff": false,
        "className": "",
        "x": 620,
        "y": 160,
        "wires": []
    },
    {
        "id": "chart_temp",
        "type": "ui_chart",
        "z": "tab_aula_mqtt",
        "name": "Chart Temperatura",
        "group": "ui_group_temp",
        "order": 2,
        "width": 0,
        "height": 0,
        "label": "Histórico de Temperatura",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "0",
        "ymax": "50",
        "removeOlder": 10,
        "removeOlderPoints": "",
        "removeOlderUnit": "60",
        "cutout": 0,
        "useOneColor": false,
        "useUTC": false,
        "colors": ["#1f77b4", "#aec7e8", "#ff7f0e", "#2ca02c", "#98df8a", "#d62728", "#ff9896", "#9467bd", "#c5b0d5"],
        "outputs": 1,
        "useDifferentColor": false,
        "className": "",
        "x": 620,
        "y": 240,
        "wires": [[]]
    }
]
